### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by rs03** [rs03/JAVA-Powermockito#1]
I am writing unit test code for rest API and want to mock database call(static methods).
I am using powermockito for the same .
Unit test file
package Tests;

import com.koopid.apex.API.restclient.;
import static org.junit.Assert.;
import Tests.serviceinfo2;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import javax.ws.rs.core.Application;
import javax.ws.rs.core.Response;

import org.glassfish.jersey.client.ClientConfig;
import org.glassfish.jersey.media.multipart.MultiPartFeature;
import org.glassfish.jersey.server.ResourceConfig;
import org.glassfish.jersey.test.JerseyTest;
import org.glassfish.jersey.test.TestProperties;
import org.junit.Test;

import com.koopid.apex.API.rest.controller.LogControllerLua;

//import static com.jayway.restassured.RestAssured.expect;
//import static com.jayway.restassured.RestAssured.get;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.nullValue;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import java.util.Arrays;
import java.util.List;

import org.junit.Test;
import com.google.gson.Gson;
import com.koopid.apex.API.rest.service.LoggerServiceLua;
import com.koopid.apex.API.rest.service.*;

import static org.mockito.Mockito.*;

import java.util.Arrays;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import javax.ws.rs.core.Application;

import java.util.Arrays;
import java.util.List;

@RunWith(PowerMockRunner.class)

@preparefortest(com.koopid.apex.API.restclient.DBRestClient.class)
public class LogControllerLuaTest extends JerseyTest {

LoggerServiceLua loggerServiceLua = new LoggerServiceLua();
LogControllerLua logControllerLua;
DBRestClient dbRestClient;

@Override
protected Application configure() {

    //return new ResourceConfig(JerseyConfig.class);
	//MockitoAnnotations.initMocks(this);
	System.out.println("in config");
	ResourceConfig resourceConfig = new ResourceConfig();

    resourceConfig.register(MultiPartFeature.class);
    resourceConfig.register(DBRestClient.class);
    resourceConfig.register(LoggerServiceLua.class);
    resourceConfig.register(LogControllerLua.class);
    
    System.out.println("in config end");
    return resourceConfig;
}
    
  

     
    @Test
    public void testgetLogServerInfo() throws Exception
    {
    	
    	System.out.println("executing in test");
    	String serviceinfo = new String("{\"_id\":\"log_server\",\"_rev\":\"jfdjgdgd\",\"ip_address\":\"192.3.4.1\",\"port\":\"5144\"}");
    	PowerMockito.mock(DBRestClient.class);
    	System.out.println("executing in test2");
    	
    	PowerMockito.when(DBRestClient.getLogServerInfo()).thenReturn(serviceinfo);
        System.out.println("in test 1 end");
       
    	String response = target("/getLogServerInfo").request().get(String.class);
        loggerServiceLua.getLogServerInfo();
    	
    	System.out.println("---------------------");
    	
        System.out.println("in test 3 end");
      
        PowerMockito.verifyStatic(Mockito.never());
        DBRestClient.getLogServerInfo();
        //verify(DBRestClient.class, times(1)).getLogServerInfo();
        System.out.println("in test 4 end");
    
    }
}
ERROR traces
java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
com/sun/net/httpserver/spi/HttpServerProvider$1.run()Ljava/lang/Object; @27: invokestatic
Reason:
Type 'sun/net/httpserver/DefaultHttpServerProvider' (current frame, stack[0]) is not assignable to 'com/sun/net/httpserver/spi/HttpServerProvider'
Current Frame:
bci: @27
flags: { }
locals: { 'com/sun/net/httpserver/spi/HttpServerProvider$1' }
stack: { 'sun/net/httpserver/DefaultHttpServerProvider' }
Bytecode:
0x0000000: b800 2599 0007 b800 27b0 b800 2699 0007
0x0000010: b800 27b0 bb00 1b59 b700 2ab8 0028 57b8
0x0000020: 0027 b0
Stackmap Table:
same_frame(@10)
same_frame(@20)

at com.sun.net.httpserver.spi.HttpServerProvider.provider(HttpServerProvider.java:165)
at com.sun.net.httpserver.HttpServer.create(HttpServer.java:129)
at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:259)
at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:206)
at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:111)
at org.glassfish.jersey.test.jdkhttp.JdkHttpServerTestContainerFactory$JdkHttpServerTestContainer.<init>(JdkHttpServerTestContainerFactory.java:82)
at org.glassfish.jersey.test.jdkhttp.JdkHttpServerTestContainerFactory$JdkHttpServerTestContainer.<init>(JdkHttpServerTestContainerFactory.java:67)
at org.glassfish.jersey.test.jdkhttp.JdkHttpServerTestContainerFactory.create(JdkHttpServerTestContainerFactory.java:125)
at org.glassfish.jersey.test.JerseyTest.createTestContainer(JerseyTest.java:277)
at org.glassfish.jersey.test.JerseyTest.setUp(JerseyTest.java:609)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106)
at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

What could be the reason for this error?

**Comment by rs03** [comment]
Resolved above issue by adding @org.powermock.core.classloader.annotations.PowerMockIgnore({"javax.ws.*", "org.glassfish.*","javax.net.ssl.*"})

and by replacing .mock by .mockstatic
